### ISSUE TITLE
error with formatting

### ISSUE THREAD

**Issue by gristlekinginc** [Anashost/WeatherXM-Home-Assistant#2]
Added this into my yaml and getting this:
end of the stream or a document separator is expected (127:1)

 124 |       
 125 | # WeatherXM
 126 | 
 127 | - platform: rest 
-------^
 128 |   name: weatherxm_sensor
 129 |   resource: 'https://api.weathe ...

**Comment by Anashost** [comment]
Yes I've just noticed that there was a syntax error (some spaces were missing) I've fixed it. Copy the code again and try.

Edit: I noticed another syntax error, now it shoud 100% work. Just make sure to use the copy icon, to copy the code, and paste it to an empty line in your sensors.yaml.

**Comment by gristlekinginc** [comment]
Super, thanks!  This'll sound stupid, but...where do I see the sensors so I can pull in the info and display it?  I'm looking in Entities and not seeing anything.  Sorry, new to HA!

**Comment by Anashost** [comment]
It's ok, HA is always confusing when you start using it. So, after you've add the yaml and restart HA, you can see the entities by going to:
developer tools -> states, then search for weatherXM, you should find all sensors related to weatherXM and it's states that we pulled from the api. (Weather data will update automatically every 5 minutes).

In your UI, you can use the default entity/entities card, to display the sensors you want. of course you can use any other cards you like, like the popular Mushroom cards that you can download using HACS.

**Comment by Anashost** [comment]
If you live in US and want to show the temperature in Fahrenheit instead of Celsius, then add this additional sensor to sensors.yaml, and restart:

```
  - platform: template
    sensors:
      weatherxm_temperature_fahrenheit:
        value_template: "{{ (state_attr('sensor.weatherxm_sensor', 'temperature') * 9/5 + 32) |round(1)}}"
        device_class: temperature
        unit_of_measurement:  "°C"

  - platform: template
    sensors:
      weatherxm_feels_like_fahrenheit:
        value_template: "{{ (state_attr('sensor.weatherxm_sensor', 'feels_like') * 9/5 + 32) |round(1)}}"
        device_class: temperature
        unit_of_measurement:  "°C"
```

**Comment by gristlekinginc** [comment]
Thanks.  Still not seeing any of the Sensors in Developer tools -> States.

**Comment by Anashost** [comment]
Just to make sure, you added the yaml to your sensors.yaml and restarted HA?

And make sure you add this line to your configuration.yaml
`sensor: !include sensors.yaml` and restart

**Comment by gristlekinginc** [comment]
I hadn't added that line to the configuration.yaml, that was it! Thank you!

**Comment by Anashost** [comment]
I will close this issue for now, if you have any other issues or questions, open a new issue.
